# Anna KaRNNa

In this notebook, we'll build a character-wise RNN trained on Anna Karenina.



<img src="assets/charseq.jpeg" width="500">

In [4]:
import time
from collections import namedtuple

import numpy as np
import tensorflow as tf

In [5]:
!pwd

/home/abhay/Documents/LearnersHeaven/courses_N_sessions/MasterinDataScience/char-RNN-TensorFlow-master


First we'll load the text file and convert it into integers for our network to use. Here I'm creating a couple dictionaries to convert the characters to and from integers. Encoding the characters as integers makes it easier to use as input in the network.

In [6]:
with open('anna.txt', 'r') as f:
    text=f.read()

In [7]:
vocab = set(text)
vocab_to_int = {c: i for i, c in enumerate(vocab)}
int_to_vocab = dict(enumerate(vocab))
encoded = np.array([vocab_to_int[c] for c in text], dtype=np.int32)

In [8]:
encoded

array([16, 58, 56, ..., 40,  2, 50], dtype=int32)

Let's check out the first 100 characters, make sure everything is peachy. 

In [27]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

And we can see the characters encoded as integers.

In [28]:
encoded[:100]

array([30, 65, 56, 73, 77, 60, 75,  2, 15,  0,  0,  0, 37, 56, 73, 73, 80,
        2, 63, 56, 68, 64, 69, 64, 60, 74,  2, 56, 75, 60,  2, 56, 69, 69,
        2, 56, 69, 64, 66, 60, 25,  2, 60, 79, 60, 75, 80,  2, 76, 71, 65,
       56, 73, 73, 80,  2, 63, 56, 68, 64, 69, 80,  2, 64, 74,  2, 76, 71,
       65, 56, 73, 73, 80,  2, 64, 71,  2, 64, 77, 74,  2, 70, 78, 71,  0,
       78, 56, 80, 14,  0,  0, 32, 79, 60, 75, 80, 77, 65, 64, 71], dtype=int32)

In [10]:
encoded.shape

(1985223,)

Since the network is working with individual characters, it's similar to a classification problem in which we are trying to predict the next character from the previous text.  Here's how many 'classes' our network has to pick from.

In [35]:
len(vocab)

83

## Making training mini-batches

Here is where we'll make our mini-batches for training. Remember that we want our batches to be multiple sequences of some desired number of sequence steps. Considering a simple example, our batches would look like this:

<img src="assets/sequence_batching@1x.png" width=500px>


<br>
We have our text encoded as integers as one long array in `encoded`. Let's create a function that will give us an iterator for our batches. I like using [generator functions](https://jeffknupp.com/blog/2013/04/07/improve-your-python-yield-and-generators-explained/) to do this. Then we can pass `encoded` into this function and get our batch generator.

The first thing we need to do is discard some of the text so we only have completely full batches. Each batch contains $N \times M$ characters, where $N$ is the batch size (the number of sequences) and $M$ is the number of steps. Then, to get the number of batches we can make from some array `arr`, you divide the length of `arr` by the batch size. Once you know the number of batches and the batch size, you can get the total number of characters to keep.

After that, we need to split `arr` into $N$ sequences. You can do this using `arr.reshape(size)` where `size` is a tuple containing the dimensions sizes of the reshaped array. We know we want $N$ sequences (`n_seqs` below), let's make that the size of the first dimension. For the second dimension, you can use `-1` as a placeholder in the size, it'll fill up the array with the appropriate data for you. After this, you should have an array that is $N \times (M * K)$ where $K$ is the number of batches.

Now that we have this array, we can iterate through it to get our batches. The idea is each batch is a $N \times M$ window on the array. For each subsequent batch, the window moves over by `n_steps`. We also want to create both the input and target arrays. Remember that the targets are the inputs shifted over one character. You'll usually see the first input character used as the last target character, so something like this:
```python
y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
```
where `x` is the input batch and `y` is the target batch.

The way I like to do this window is use `range` to take steps of size `n_steps` from $0$ to `arr.shape[1]`, the total number of steps in each sequence. That way, the integers you get from `range` always point to the start of a batch, and each window is `n_steps` wide.

> **Exercise:** Write the code for creating batches in the function below. The exercises in this notebook _will not be easy_. I've provided a notebook with solutions alongside this notebook. If you get stuck, checkout the solutions. The most important thing is that you don't copy and paste the code into here, **type out the solution code yourself.**

In [36]:
def get_batches(arr, n_seqs, n_steps):
    '''Create a generator that returns batches of size
       n_seqs x n_steps from arr.
       
       Arguments
       ---------
       arr: Array you want to make batches from
       n_seqs: Batch size, the number of sequences per batch
       n_steps: Number of sequence steps per batch
    '''
    # Get the number of characters per batch and number of batches we can make
    characters_per_batch = n_seqs * n_steps
    n_batches = len(arr) // characters_per_batch
    
    # Keep only enough characters to make full batches
    arr = arr[:n_batches * characters_per_batch]
    
    # Reshape into n_seqs rows
    arr = arr.reshape((n_seqs, -1))
    
    for n in range(0, arr.shape[1], n_steps):
        # The features
        x = arr[:, n:n+n_steps]
        # The targets, shifted by one
        y = np.zeros_like(x)
        y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
        yield x, y

Now I'll make my data sets and we can check out what's going on here. Here I'm going to use a batch size of 10 and 50 sequence steps.

In [37]:
batches = get_batches(encoded, 10, 50)
x, y = next(batches)

In [38]:
print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])

('x\n', array([[30, 65, 56, 73, 77, 60, 75,  2, 15,  0],
       [ 2, 56, 68,  2, 71, 70, 77,  2, 62, 70],
       [79, 64, 71, 14,  0,  0,  3, 52, 60, 74],
       [71,  2, 61, 76, 75, 64, 71, 62,  2, 65],
       [ 2, 64, 77,  2, 64, 74, 12,  2, 74, 64],
       [ 2, 36, 77,  2, 78, 56, 74,  0, 70, 71],
       [65, 60, 71,  2, 58, 70, 68, 60,  2, 63],
       [25,  2, 59, 76, 77,  2, 71, 70, 78,  2],
       [77,  2, 64, 74, 71,  6, 77, 14,  2, 49],
       [ 2, 74, 56, 64, 61,  2, 77, 70,  2, 65]], dtype=int32))
('\ny\n', array([[65, 56, 73, 77, 60, 75,  2, 15,  0,  0],
       [56, 68,  2, 71, 70, 77,  2, 62, 70, 64],
       [64, 71, 14,  0,  0,  3, 52, 60, 74, 12],
       [ 2, 61, 76, 75, 64, 71, 62,  2, 65, 64],
       [64, 77,  2, 64, 74, 12,  2, 74, 64, 75],
       [36, 77,  2, 78, 56, 74,  0, 70, 71, 69],
       [60, 71,  2, 58, 70, 68, 60,  2, 63, 70],
       [ 2, 59, 76, 77,  2, 71, 70, 78,  2, 74],
       [ 2, 64, 74, 71,  6, 77, 14,  2, 49, 65],
       [74, 56, 64, 61,  2, 77, 70, 

In [39]:
x.shape, y.shape

((10, 50), (10, 50))

If you implemented `get_batches` correctly, the above output should look something like 
```
x
 [[55 63 69 22  6 76 45  5 16 35]
 [ 5 69  1  5 12 52  6  5 56 52]
 [48 29 12 61 35 35  8 64 76 78]
 [12  5 24 39 45 29 12 56  5 63]
 [ 5 29  6  5 29 78 28  5 78 29]
 [ 5 13  6  5 36 69 78 35 52 12]
 [63 76 12  5 18 52  1 76  5 58]
 [34  5 73 39  6  5 12 52 36  5]
 [ 6  5 29 78 12 79  6 61  5 59]
 [ 5 78 69 29 24  5  6 52  5 63]]

y
 [[63 69 22  6 76 45  5 16 35 35]
 [69  1  5 12 52  6  5 56 52 29]
 [29 12 61 35 35  8 64 76 78 28]
 [ 5 24 39 45 29 12 56  5 63 29]
 [29  6  5 29 78 28  5 78 29 45]
 [13  6  5 36 69 78 35 52 12 43]
 [76 12  5 18 52  1 76  5 58 52]
 [ 5 73 39  6  5 12 52 36  5 78]
 [ 5 29 78 12 79  6 61  5 59 63]
 [78 69 29 24  5  6 52  5 63 76]]
 ```
 although the exact numbers will be different. Check to make sure the data is shifted over one step for `y`.

## Building the model

Below is where you'll build the network. We'll break it up into parts so it's easier to reason about each bit. Then we can connect them up into the whole network.

<img src="assets/charRNN.png" width=500px>


### Inputs

First off we'll create our input placeholders. As usual we need placeholders for the training data and the targets. We'll also create a placeholder for dropout layers called `keep_prob`. This will be a scalar, that is a 0-D tensor. To make a scalar, you create a placeholder without giving it a size.

> **Exercise:** Create the input placeholders in the function below.

In [9]:
def build_inputs(batch_size, num_steps):
    ''' Define placeholders for inputs, targets, and dropout 
    
        Arguments
        ---------
        batch_size: Batch size, number of sequences per batch
        num_steps: Number of sequence steps in a batch
        
    '''
    # Declare placeholders we'll feed into the graph
    inputs = tf.placeholder(tf.int32, [batch_size, num_steps], name='inputs')
    targets = tf.placeholder(tf.int32, [batch_size, num_steps], name='targets')
    
    # Keep probability placeholder for drop out layers
    keep_prob = tf.placeholder(tf.float32, name='keep_prob')
    
    return inputs, targets, keep_prob

### LSTM Cell

Here we will create the LSTM cell we'll use in the hidden layer. We'll use this cell as a building block for the RNN. So we aren't actually defining the RNN here, just the type of cell we'll use in the hidden layer.

We first create a basic LSTM cell with

```python
lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
```

where `num_units` is the number of units in the hidden layers in the cell. Then we can add dropout by wrapping it with 

```python
tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
```
You pass in a cell and it will automatically add dropout to the inputs or outputs. Finally, we can stack up the LSTM cells into layers with [`tf.contrib.rnn.MultiRNNCell`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/contrib/rnn/MultiRNNCell). With this, you pass in a list of cells and it will send the output of one cell into the next cell. Previously with TensorFlow 1.0, you could do this

```python
tf.contrib.rnn.MultiRNNCell([cell]*num_layers)
```

This might look a little weird if you know Python well because this will create a list of the same `cell` object. However, TensorFlow 1.0 will create different weight matrices for all `cell` objects. But, starting with TensorFlow 1.1 you actually need to create new cell objects in the list. To get it to work in TensorFlow 1.1, it should look like

```python
def build_cell(num_units, keep_prob):
    lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
    drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
    
    return drop
    
tf.contrib.rnn.MultiRNNCell([build_cell(num_units, keep_prob) for _ in range(num_layers)])
```

Even though this is actually multiple LSTM cells stacked on each other, you can treat the multiple layers as one cell.

We also need to create an initial cell state of all zeros. This can be done like so

```python
initial_state = cell.zero_state(batch_size, tf.float32)
```

Below, we implement the `build_lstm` function to create these LSTM cells and the initial state.

In [10]:
def build_lstm(lstm_size, num_layers, batch_size, keep_prob):
    ''' Build LSTM cell.
    
        Arguments
        ---------
        keep_prob: Scalar tensor (tf.placeholder) for the dropout keep probability
        lstm_size: Size of the hidden layers in the LSTM cells
        num_layers: Number of LSTM layers
        batch_size: Batch size

    '''   
    def build_cell(lstm_size, keep_prob):
        
        ### Build the LSTM Cell
        # Use a basic LSTM cell
        lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)
        
        # Add dropout to the cell outputs
        drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
        
        return drop
    
    # Stack up multiple LSTM layers, for deep learning
    cell = tf.contrib.rnn.MultiRNNCell([build_cell(lstm_size, keep_prob) for _ in range(num_layers)])
    initial_state = cell.zero_state(batch_size, tf.float32)
    
    return cell, initial_state

### RNN Output

Here we'll create the output layer. We need to connect the output of the RNN cells to a full connected layer with a softmax output. The softmax output gives us a probability distribution we can use to predict the next character, so we want this layer to have size $C$, the number of classes/characters we have in our text.

If our input has batch size $N$, number of steps $M$, and the hidden layer has $L$ hidden units, then the output is a 3D tensor with size $N \times M \times L$. The output of each LSTM cell has size $L$, we have $M$ of them, one for each sequence step, and we have $N$ sequences. So the total size is $N \times M \times L$. 

We are using the same fully connected layer, the same weights, for each of the outputs. Then, to make things easier, we should reshape the outputs into a 2D tensor with shape $(M * N) \times L$. That is, one row for each sequence and step, where the values of each row are the output from the LSTM cells. We get the LSTM output as a list, `lstm_output`. First we need to concatenate this whole list into one array with [`tf.concat`](https://www.tensorflow.org/api_docs/python/tf/concat). Then, reshape it (with `tf.reshape`) to size $(M * N) \times L$.

One we have the outputs reshaped, we can do the matrix multiplication with the weights. We need to wrap the weight and bias variables in a variable scope with `tf.variable_scope(scope_name)` because there are weights being created in the LSTM cells. TensorFlow will throw an error if the weights created here have the same names as the weights created in the LSTM cells, which they will be default. To avoid this, we wrap the variables in a variable scope so we can give them unique names.

> **Exercise:** Implement the output layer in the function below.

In [11]:
def build_output(lstm_output, in_size, out_size):
    ''' Build a softmax layer, return the softmax output and logits.
    
        Arguments
        ---------
        
        lstm_output: List of output tensors from the LSTM layer
        in_size: Size of the input tensor, for example, size of the LSTM cells
        out_size: Size of this softmax layer
    
    '''

    # Reshape output so it's a bunch of rows, one row for each step for each sequence.
    # Concatenate lstm_output over axis 1 (the columns)
    seq_output = tf.concat(lstm_output, axis=1)
    # Reshape seq_output to a 2D tensor with lstm_size columns
    x = tf.reshape(seq_output, [-1, in_size])
    
    # Connect the RNN outputs to a softmax layer
    with tf.variable_scope('softmax'):
        # Create the weight and bias variables here
        softmax_w = tf.Variable(tf.truncated_normal([in_size, out_size], stddev=0.1))
        softmax_b = tf.Variable(tf.zeros([out_size]))
    
    # Since output is a bunch of rows of RNN cell outputs, logits will be a bunch
    # of rows of logit outputs, one for each step and sequence
    logits = tf.matmul(x, softmax_w) + softmax_b
    
    # Use softmax to get the probabilities for predicted characters
    out = tf.nn.softmax(logits, name='predictions')
    
    return out, logits

### Training loss

Next up is the training loss. We get the logits and targets and calculate the softmax cross-entropy loss. First we need to one-hot encode the targets, we're getting them as encoded characters. Then, reshape the one-hot targets so it's a 2D tensor with size $(M*N) \times C$ where $C$ is the number of classes/characters we have. Remember that we reshaped the LSTM outputs and ran them through a fully connected layer with $C$ units. So our logits will also have size $(M*N) \times C$.

Then we run the logits and targets through `tf.nn.softmax_cross_entropy_with_logits` and find the mean to get the loss.

>**Exercise:** Implement the loss calculation in the function below.

In [12]:
def build_loss(logits, targets, lstm_size, num_classes):
    ''' Calculate the loss from the logits and the targets.
    
        Arguments
        ---------
        logits: Logits from final fully connected layer
        targets: Targets for supervised learning
        lstm_size: Number of LSTM hidden units
        num_classes: Number of classes in targets
        
    '''
    
    # One-hot encode targets and reshape to match logits, one row per sequence per step
    y_one_hot = tf.one_hot(targets, num_classes)
    y_reshaped = tf.reshape(y_one_hot, logits.get_shape())
    
    # Softmax cross entropy loss
    loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y_reshaped, logits=logits))
    
    return loss

### Optimizer

Here we build the optimizer. Normal RNNs have have issues gradients exploding and disappearing. LSTMs fix the disappearance problem, but the gradients can still grow without bound. To fix this, we can clip the gradients above some threshold. That is, if a gradient is larger than that threshold, we set it to the threshold. This will ensure the gradients never grow overly large. Then we use an AdamOptimizer for the learning step.

In [13]:
def build_optimizer(loss, learning_rate, grad_clip):
    ''' Build optmizer for training, using gradient clipping.
    
        Arguments:
        loss: Network loss
        learning_rate: Learning rate for optimizer
    
    '''
    
    # Optimizer for training, using gradient clipping to control exploding gradients
    tvars = tf.trainable_variables()
    grads, _ = tf.clip_by_global_norm(tf.gradients(loss, tvars), grad_clip)
    train_op = tf.train.AdamOptimizer(learning_rate)
    optimizer = train_op.apply_gradients(zip(grads, tvars))
    
    return optimizer

### Build the network

Now we can put all the pieces together and build a class for the network. To actually run data through the LSTM cells, we will use [`tf.nn.dynamic_rnn`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/nn/dynamic_rnn). This function will pass the hidden and cell states across LSTM cells appropriately for us. It returns the outputs for each LSTM cell at each step for each sequence in the mini-batch. It also gives us the final LSTM state. We want to save this state as `final_state` so we can pass it to the first LSTM cell in the the next mini-batch run. For `tf.nn.dynamic_rnn`, we pass in the cell and initial state we get from `build_lstm`, as well as our input sequences. Also, we need to one-hot encode the inputs before going into the RNN. 

> **Exercise:** Use the functions you've implemented previously and `tf.nn.dynamic_rnn` to build the network.

In [14]:
class CharRNN:
    
    def __init__(self, num_classes, batch_size=64, num_steps=50, 
                       lstm_size=128, num_layers=2, learning_rate=0.001, 
                       grad_clip=5, sampling=False):
    
        # When we're using this network for sampling later, we'll be passing in
        # one character at a time, so providing an option for that
        if sampling == True:
            batch_size, num_steps = 1, 1
        else:
            batch_size, num_steps = batch_size, num_steps

        tf.reset_default_graph()
        
        # Build the input placeholder tensors
        self.inputs, self.targets, self.keep_prob = build_inputs(batch_size=batch_size, num_steps=num_steps)

        # Build the LSTM cell
        cell, self.initial_state = build_lstm(lstm_size=lstm_size, num_layers=num_layers, \
                                              batch_size=batch_size, keep_prob=self.keep_prob)

        ### Run the data through the RNN layers
        # First, one-hot encode the input tokens
        x_one_hot = tf.one_hot(self.inputs, num_classes)
        
        # Run each sequence step through the RNN with tf.nn.dynamic_rnn 
        outputs, state = tf.nn.dynamic_rnn(cell, x_one_hot, initial_state=self.initial_state)
        self.final_state = state
        
        # Get softmax predictions and logits
        self.prediction, self.logits = build_output(outputs, lstm_size, num_classes)
        
        # Loss and optimizer (with gradient clipping)
        self.loss = build_loss(self.logits, self.targets, lstm_size, num_classes)
        self.optimizer = build_optimizer(self.loss, learning_rate, grad_clip)

## Hyperparameters

Here are the hyperparameters for the network.

* `batch_size` - Number of sequences running through the network in one pass.
* `num_steps` - Number of characters in the sequence the network is trained on. Larger is better typically, the network will learn more long range dependencies. But it takes longer to train. 100 is typically a good number here.
* `lstm_size` - The number of units in the hidden layers.
* `num_layers` - Number of hidden LSTM layers to use
* `learning_rate` - Learning rate for training
* `keep_prob` - The dropout keep probability when training. If you're network is overfitting, try decreasing this.

Here's some good advice from Andrej Karpathy on training the network. I'm going to copy it in here for your benefit, but also link to [where it originally came from](https://github.com/karpathy/char-rnn#tips-and-tricks).

> ## Tips and Tricks

>### Monitoring Validation Loss vs. Training Loss
>If you're somewhat new to Machine Learning or Neural Networks it can take a bit of expertise to get good models. The most important quantity to keep track of is the difference between your training loss (printed during training) and the validation loss (printed once in a while when the RNN is run on the validation data (by default every 1000 iterations)). In particular:

> - If your training loss is much lower than validation loss then this means the network might be **overfitting**. Solutions to this are to decrease your network size, or to increase dropout. For example you could try dropout of 0.5 and so on.
> - If your training/validation loss are about equal then your model is **underfitting**. Increase the size of your model (either number of layers or the raw number of neurons per layer)

> ### Approximate number of parameters

> The two most important parameters that control the model are `lstm_size` and `num_layers`. I would advise that you always use `num_layers` of either 2/3. The `lstm_size` can be adjusted based on how much data you have. The two important quantities to keep track of here are:

> - The number of parameters in your model. This is printed when you start training.
> - The size of your dataset. 1MB file is approximately 1 million characters.

>These two should be about the same order of magnitude. It's a little tricky to tell. Here are some examples:

> - I have a 100MB dataset and I'm using the default parameter settings (which currently print 150K parameters). My data size is significantly larger (100 mil >> 0.15 mil), so I expect to heavily underfit. I am thinking I can comfortably afford to make `lstm_size` larger.
> - I have a 10MB dataset and running a 10 million parameter model. I'm slightly nervous and I'm carefully monitoring my validation loss. If it's larger than my training loss then I may want to try to increase dropout a bit and see if that helps the validation loss.

> ### Best models strategy

>The winning strategy to obtaining very good models (if you have the compute time) is to always err on making the network larger (as large as you're willing to wait for it to compute) and then try different dropout values (between 0,1). Whatever model has the best validation performance (the loss, written in the checkpoint filename, low is good) is the one you should use in the end.

>It is very common in deep learning to run many different models with many different hyperparameter settings, and in the end take whatever checkpoint gave the best validation performance.

>By the way, the size of your training and validation splits are also parameters. Make sure you have a decent amount of data in your validation set or otherwise the validation performance will be noisy and not very informative.

In [15]:
batch_size = 10         # Sequences per batch
num_steps = 50          # Number of sequence steps per batch
lstm_size = 128         # Size of hidden layers in LSTMs
num_layers = 2          # Number of LSTM layers
learning_rate = 0.01    # Learning rate
keep_prob = 0.5         # Dropout keep probability

## Time for training

This is typical training code, passing inputs and targets into the network, then running the optimizer. Here we also get back the final LSTM state for the mini-batch. Then, we pass that state back into the network so the next batch can continue the state from the previous batch. And every so often (set by `save_every_n`) I save a checkpoint.

Here I'm saving checkpoints with the format

`i{iteration number}_l{# hidden layer units}.ckpt`

> **Exercise:** Set the hyperparameters above to train the network. Watch the training loss, it should be consistently dropping. Also, I highly advise running this on a GPU.

In [ ]:
epochs = 20
# Save every N iterations
save_every_n = 200

model = CharRNN(len(vocab), batch_size=batch_size, num_steps=num_steps,
                lstm_size=lstm_size, num_layers=num_layers, 
                learning_rate=learning_rate)

saver = tf.train.Saver(max_to_keep=100)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    # Use the line below to load a checkpoint and resume training
    #saver.restore(sess, 'checkpoints/______.ckpt')
    counter = 0
    for e in range(epochs):
        # Train network
        new_state = sess.run(model.initial_state)
        loss = 0
        for x, y in get_batches(encoded, batch_size, num_steps):
            counter += 1
            start = time.time()
            feed = {model.inputs: x,
                    model.targets: y,
                    model.keep_prob: keep_prob,
                    model.initial_state: new_state}
            batch_loss, new_state, _ = sess.run([model.loss, 
                                                 model.final_state, 
                                                 model.optimizer], 
                                                 feed_dict=feed)
            
            end = time.time()
            print('Epoch: {}/{}... '.format(e+1, epochs),
                  'Training Step: {}... '.format(counter),
                  'Training loss: {:.4f}... '.format(batch_loss),
                  '{:.4f} sec/batch'.format((end-start)))
        
            if (counter % save_every_n == 0):
                saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))
    
    saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))

('Epoch: 1/20... ', 'Training Step: 1... ', 'Training loss: 4.4179... ', '0.3581 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2... ', 'Training loss: 4.2798... ', '0.1153 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3... ', 'Training loss: 3.5391... ', '0.1594 sec/batch')
('Epoch: 1/20... ', 'Training Step: 4... ', 'Training loss: 3.4319... ', '0.0980 sec/batch')
('Epoch: 1/20... ', 'Training Step: 5... ', 'Training loss: 3.2804... ', '0.1452 sec/batch')
('Epoch: 1/20... ', 'Training Step: 6... ', 'Training loss: 3.3634... ', '0.1302 sec/batch')
('Epoch: 1/20... ', 'Training Step: 7... ', 'Training loss: 3.2449... ', '0.1592 sec/batch')
('Epoch: 1/20... ', 'Training Step: 8... ', 'Training loss: 3.2006... ', '0.1373 sec/batch')
('Epoch: 1/20... ', 'Training Step: 9... ', 'Training loss: 3.2236... ', '0.2159 sec/batch')
('Epoch: 1/20... ', 'Training Step: 10... ', 'Training loss: 3.2501... ', '0.2297 sec/batch')
('Epoch: 1/20... ', 'Training Step: 11... ', 'Training loss: 3.2813..

('Epoch: 1/20... ', 'Training Step: 89... ', 'Training loss: 2.7010... ', '0.1349 sec/batch')
('Epoch: 1/20... ', 'Training Step: 90... ', 'Training loss: 2.7724... ', '0.2626 sec/batch')
('Epoch: 1/20... ', 'Training Step: 91... ', 'Training loss: 2.7875... ', '0.2337 sec/batch')
('Epoch: 1/20... ', 'Training Step: 92... ', 'Training loss: 2.8141... ', '0.1727 sec/batch')
('Epoch: 1/20... ', 'Training Step: 93... ', 'Training loss: 2.8302... ', '0.1792 sec/batch')
('Epoch: 1/20... ', 'Training Step: 94... ', 'Training loss: 2.8722... ', '0.1314 sec/batch')
('Epoch: 1/20... ', 'Training Step: 95... ', 'Training loss: 2.7796... ', '0.1580 sec/batch')
('Epoch: 1/20... ', 'Training Step: 96... ', 'Training loss: 2.6591... ', '0.1217 sec/batch')
('Epoch: 1/20... ', 'Training Step: 97... ', 'Training loss: 2.8205... ', '0.1361 sec/batch')
('Epoch: 1/20... ', 'Training Step: 98... ', 'Training loss: 2.7587... ', '0.1046 sec/batch')
('Epoch: 1/20... ', 'Training Step: 99... ', 'Training loss:

('Epoch: 1/20... ', 'Training Step: 176... ', 'Training loss: 2.3596... ', '0.1381 sec/batch')
('Epoch: 1/20... ', 'Training Step: 177... ', 'Training loss: 2.3414... ', '0.0929 sec/batch')
('Epoch: 1/20... ', 'Training Step: 178... ', 'Training loss: 2.4275... ', '0.0981 sec/batch')
('Epoch: 1/20... ', 'Training Step: 179... ', 'Training loss: 2.5474... ', '0.1433 sec/batch')
('Epoch: 1/20... ', 'Training Step: 180... ', 'Training loss: 2.4004... ', '0.0986 sec/batch')
('Epoch: 1/20... ', 'Training Step: 181... ', 'Training loss: 2.3092... ', '0.1465 sec/batch')
('Epoch: 1/20... ', 'Training Step: 182... ', 'Training loss: 2.4388... ', '0.1428 sec/batch')
('Epoch: 1/20... ', 'Training Step: 183... ', 'Training loss: 2.5001... ', '0.1266 sec/batch')
('Epoch: 1/20... ', 'Training Step: 184... ', 'Training loss: 2.4509... ', '0.1200 sec/batch')
('Epoch: 1/20... ', 'Training Step: 185... ', 'Training loss: 2.4770... ', '0.2024 sec/batch')
('Epoch: 1/20... ', 'Training Step: 186... ', 'Tra

('Epoch: 1/20... ', 'Training Step: 264... ', 'Training loss: 2.3249... ', '0.1597 sec/batch')
('Epoch: 1/20... ', 'Training Step: 265... ', 'Training loss: 2.2475... ', '0.2978 sec/batch')
('Epoch: 1/20... ', 'Training Step: 266... ', 'Training loss: 2.2941... ', '0.3057 sec/batch')
('Epoch: 1/20... ', 'Training Step: 267... ', 'Training loss: 2.2785... ', '0.3747 sec/batch')
('Epoch: 1/20... ', 'Training Step: 268... ', 'Training loss: 2.3506... ', '0.2457 sec/batch')
('Epoch: 1/20... ', 'Training Step: 269... ', 'Training loss: 2.3718... ', '0.1284 sec/batch')
('Epoch: 1/20... ', 'Training Step: 270... ', 'Training loss: 2.4358... ', '0.1269 sec/batch')
('Epoch: 1/20... ', 'Training Step: 271... ', 'Training loss: 2.3755... ', '0.1446 sec/batch')
('Epoch: 1/20... ', 'Training Step: 272... ', 'Training loss: 2.3325... ', '0.1683 sec/batch')
('Epoch: 1/20... ', 'Training Step: 273... ', 'Training loss: 2.4661... ', '0.1130 sec/batch')
('Epoch: 1/20... ', 'Training Step: 274... ', 'Tra

('Epoch: 1/20... ', 'Training Step: 352... ', 'Training loss: 2.2606... ', '0.1633 sec/batch')
('Epoch: 1/20... ', 'Training Step: 353... ', 'Training loss: 2.3967... ', '0.1443 sec/batch')
('Epoch: 1/20... ', 'Training Step: 354... ', 'Training loss: 2.2905... ', '0.1863 sec/batch')
('Epoch: 1/20... ', 'Training Step: 355... ', 'Training loss: 2.2858... ', '0.1330 sec/batch')
('Epoch: 1/20... ', 'Training Step: 356... ', 'Training loss: 2.3086... ', '0.1868 sec/batch')
('Epoch: 1/20... ', 'Training Step: 357... ', 'Training loss: 2.3832... ', '0.1693 sec/batch')
('Epoch: 1/20... ', 'Training Step: 358... ', 'Training loss: 2.2681... ', '0.3671 sec/batch')
('Epoch: 1/20... ', 'Training Step: 359... ', 'Training loss: 2.1841... ', '0.3143 sec/batch')
('Epoch: 1/20... ', 'Training Step: 360... ', 'Training loss: 2.3433... ', '0.3333 sec/batch')
('Epoch: 1/20... ', 'Training Step: 361... ', 'Training loss: 2.3326... ', '0.1988 sec/batch')
('Epoch: 1/20... ', 'Training Step: 362... ', 'Tra

('Epoch: 1/20... ', 'Training Step: 439... ', 'Training loss: 2.0838... ', '0.2121 sec/batch')
('Epoch: 1/20... ', 'Training Step: 440... ', 'Training loss: 2.2945... ', '0.1698 sec/batch')
('Epoch: 1/20... ', 'Training Step: 441... ', 'Training loss: 2.3162... ', '0.1501 sec/batch')
('Epoch: 1/20... ', 'Training Step: 442... ', 'Training loss: 2.0885... ', '0.1439 sec/batch')
('Epoch: 1/20... ', 'Training Step: 443... ', 'Training loss: 2.1279... ', '0.3470 sec/batch')
('Epoch: 1/20... ', 'Training Step: 444... ', 'Training loss: 2.1266... ', '0.2747 sec/batch')
('Epoch: 1/20... ', 'Training Step: 445... ', 'Training loss: 2.1779... ', '0.3065 sec/batch')
('Epoch: 1/20... ', 'Training Step: 446... ', 'Training loss: 2.1603... ', '0.1763 sec/batch')
('Epoch: 1/20... ', 'Training Step: 447... ', 'Training loss: 2.2968... ', '0.1833 sec/batch')
('Epoch: 1/20... ', 'Training Step: 448... ', 'Training loss: 2.0481... ', '0.1460 sec/batch')
('Epoch: 1/20... ', 'Training Step: 449... ', 'Tra

('Epoch: 1/20... ', 'Training Step: 527... ', 'Training loss: 2.0767... ', '0.1503 sec/batch')
('Epoch: 1/20... ', 'Training Step: 528... ', 'Training loss: 2.1813... ', '0.1649 sec/batch')
('Epoch: 1/20... ', 'Training Step: 529... ', 'Training loss: 2.1259... ', '0.1449 sec/batch')
('Epoch: 1/20... ', 'Training Step: 530... ', 'Training loss: 2.1697... ', '0.1259 sec/batch')
('Epoch: 1/20... ', 'Training Step: 531... ', 'Training loss: 2.1881... ', '0.1489 sec/batch')
('Epoch: 1/20... ', 'Training Step: 532... ', 'Training loss: 2.0986... ', '0.1128 sec/batch')
('Epoch: 1/20... ', 'Training Step: 533... ', 'Training loss: 2.0384... ', '0.1161 sec/batch')
('Epoch: 1/20... ', 'Training Step: 534... ', 'Training loss: 2.0555... ', '0.1182 sec/batch')
('Epoch: 1/20... ', 'Training Step: 535... ', 'Training loss: 2.1210... ', '0.1286 sec/batch')
('Epoch: 1/20... ', 'Training Step: 536... ', 'Training loss: 2.1686... ', '0.1231 sec/batch')
('Epoch: 1/20... ', 'Training Step: 537... ', 'Tra

('Epoch: 1/20... ', 'Training Step: 615... ', 'Training loss: 2.0601... ', '0.1804 sec/batch')
('Epoch: 1/20... ', 'Training Step: 616... ', 'Training loss: 2.0230... ', '0.1544 sec/batch')
('Epoch: 1/20... ', 'Training Step: 617... ', 'Training loss: 2.0729... ', '0.1442 sec/batch')
('Epoch: 1/20... ', 'Training Step: 618... ', 'Training loss: 2.0383... ', '0.1017 sec/batch')
('Epoch: 1/20... ', 'Training Step: 619... ', 'Training loss: 2.0167... ', '0.0984 sec/batch')
('Epoch: 1/20... ', 'Training Step: 620... ', 'Training loss: 1.9801... ', '0.1476 sec/batch')
('Epoch: 1/20... ', 'Training Step: 621... ', 'Training loss: 1.9598... ', '0.1246 sec/batch')
('Epoch: 1/20... ', 'Training Step: 622... ', 'Training loss: 2.0962... ', '0.1182 sec/batch')
('Epoch: 1/20... ', 'Training Step: 623... ', 'Training loss: 2.1433... ', '0.1029 sec/batch')
('Epoch: 1/20... ', 'Training Step: 624... ', 'Training loss: 2.0678... ', '0.1404 sec/batch')
('Epoch: 1/20... ', 'Training Step: 625... ', 'Tra

('Epoch: 1/20... ', 'Training Step: 702... ', 'Training loss: 2.1073... ', '0.1448 sec/batch')
('Epoch: 1/20... ', 'Training Step: 703... ', 'Training loss: 2.1164... ', '0.1142 sec/batch')
('Epoch: 1/20... ', 'Training Step: 704... ', 'Training loss: 2.0739... ', '0.1314 sec/batch')
('Epoch: 1/20... ', 'Training Step: 705... ', 'Training loss: 2.1245... ', '0.1181 sec/batch')
('Epoch: 1/20... ', 'Training Step: 706... ', 'Training loss: 2.1241... ', '0.1290 sec/batch')
('Epoch: 1/20... ', 'Training Step: 707... ', 'Training loss: 2.1031... ', '0.1474 sec/batch')
('Epoch: 1/20... ', 'Training Step: 708... ', 'Training loss: 2.0303... ', '0.1628 sec/batch')
('Epoch: 1/20... ', 'Training Step: 709... ', 'Training loss: 2.0910... ', '0.1167 sec/batch')
('Epoch: 1/20... ', 'Training Step: 710... ', 'Training loss: 2.1163... ', '0.1371 sec/batch')
('Epoch: 1/20... ', 'Training Step: 711... ', 'Training loss: 2.0974... ', '0.1121 sec/batch')
('Epoch: 1/20... ', 'Training Step: 712... ', 'Tra

('Epoch: 1/20... ', 'Training Step: 790... ', 'Training loss: 1.9922... ', '0.1678 sec/batch')
('Epoch: 1/20... ', 'Training Step: 791... ', 'Training loss: 2.0552... ', '0.1410 sec/batch')
('Epoch: 1/20... ', 'Training Step: 792... ', 'Training loss: 1.9296... ', '0.1568 sec/batch')
('Epoch: 1/20... ', 'Training Step: 793... ', 'Training loss: 1.9743... ', '0.1294 sec/batch')
('Epoch: 1/20... ', 'Training Step: 794... ', 'Training loss: 2.0251... ', '0.1810 sec/batch')
('Epoch: 1/20... ', 'Training Step: 795... ', 'Training loss: 1.9593... ', '0.1872 sec/batch')
('Epoch: 1/20... ', 'Training Step: 796... ', 'Training loss: 1.9453... ', '0.1487 sec/batch')
('Epoch: 1/20... ', 'Training Step: 797... ', 'Training loss: 2.0376... ', '0.1424 sec/batch')
('Epoch: 1/20... ', 'Training Step: 798... ', 'Training loss: 2.0225... ', '0.1506 sec/batch')
('Epoch: 1/20... ', 'Training Step: 799... ', 'Training loss: 2.0054... ', '0.1426 sec/batch')
('Epoch: 1/20... ', 'Training Step: 800... ', 'Tra

('Epoch: 1/20... ', 'Training Step: 877... ', 'Training loss: 1.9322... ', '0.1489 sec/batch')
('Epoch: 1/20... ', 'Training Step: 878... ', 'Training loss: 2.1607... ', '0.1316 sec/batch')
('Epoch: 1/20... ', 'Training Step: 879... ', 'Training loss: 1.9323... ', '0.1571 sec/batch')
('Epoch: 1/20... ', 'Training Step: 880... ', 'Training loss: 1.9894... ', '0.1448 sec/batch')
('Epoch: 1/20... ', 'Training Step: 881... ', 'Training loss: 2.1888... ', '0.1434 sec/batch')
('Epoch: 1/20... ', 'Training Step: 882... ', 'Training loss: 2.1777... ', '0.1170 sec/batch')
('Epoch: 1/20... ', 'Training Step: 883... ', 'Training loss: 2.0170... ', '0.1287 sec/batch')
('Epoch: 1/20... ', 'Training Step: 884... ', 'Training loss: 2.0587... ', '0.1325 sec/batch')
('Epoch: 1/20... ', 'Training Step: 885... ', 'Training loss: 1.9384... ', '0.1184 sec/batch')
('Epoch: 1/20... ', 'Training Step: 886... ', 'Training loss: 1.9704... ', '0.1263 sec/batch')
('Epoch: 1/20... ', 'Training Step: 887... ', 'Tra

('Epoch: 1/20... ', 'Training Step: 965... ', 'Training loss: 1.9728... ', '0.1403 sec/batch')
('Epoch: 1/20... ', 'Training Step: 966... ', 'Training loss: 2.0874... ', '0.1593 sec/batch')
('Epoch: 1/20... ', 'Training Step: 967... ', 'Training loss: 2.0430... ', '0.1591 sec/batch')
('Epoch: 1/20... ', 'Training Step: 968... ', 'Training loss: 1.9650... ', '0.1370 sec/batch')
('Epoch: 1/20... ', 'Training Step: 969... ', 'Training loss: 1.9581... ', '0.1448 sec/batch')
('Epoch: 1/20... ', 'Training Step: 970... ', 'Training loss: 1.8644... ', '0.1184 sec/batch')
('Epoch: 1/20... ', 'Training Step: 971... ', 'Training loss: 2.0353... ', '0.1273 sec/batch')
('Epoch: 1/20... ', 'Training Step: 972... ', 'Training loss: 2.1200... ', '0.1222 sec/batch')
('Epoch: 1/20... ', 'Training Step: 973... ', 'Training loss: 1.9634... ', '0.1357 sec/batch')
('Epoch: 1/20... ', 'Training Step: 974... ', 'Training loss: 1.9135... ', '0.1225 sec/batch')
('Epoch: 1/20... ', 'Training Step: 975... ', 'Tra

('Epoch: 1/20... ', 'Training Step: 1051... ', 'Training loss: 2.0454... ', '0.1401 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1052... ', 'Training loss: 2.0190... ', '0.1579 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1053... ', 'Training loss: 1.8332... ', '0.1235 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1054... ', 'Training loss: 1.9471... ', '0.1243 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1055... ', 'Training loss: 1.9440... ', '0.1437 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1056... ', 'Training loss: 1.9611... ', '0.1257 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1057... ', 'Training loss: 1.8091... ', '0.1295 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1058... ', 'Training loss: 1.9380... ', '0.1096 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1059... ', 'Training loss: 2.1365... ', '0.1441 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1060... ', 'Training loss: 2.0749... ', '0.1749 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1061

('Epoch: 1/20... ', 'Training Step: 1137... ', 'Training loss: 2.0567... ', '0.1583 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1138... ', 'Training loss: 2.0453... ', '0.1458 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1139... ', 'Training loss: 1.9833... ', '0.1313 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1140... ', 'Training loss: 2.1190... ', '0.1311 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1141... ', 'Training loss: 1.8286... ', '0.1305 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1142... ', 'Training loss: 1.9148... ', '0.1043 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1143... ', 'Training loss: 1.8575... ', '0.1180 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1144... ', 'Training loss: 2.2158... ', '0.1239 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1145... ', 'Training loss: 2.1284... ', '0.1368 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1146... ', 'Training loss: 1.9735... ', '0.1157 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1147

('Epoch: 1/20... ', 'Training Step: 1223... ', 'Training loss: 1.8095... ', '0.1811 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1224... ', 'Training loss: 1.9534... ', '0.1562 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1225... ', 'Training loss: 2.0641... ', '0.1732 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1226... ', 'Training loss: 1.8991... ', '0.1576 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1227... ', 'Training loss: 2.0717... ', '0.1463 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1228... ', 'Training loss: 1.9872... ', '0.1658 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1229... ', 'Training loss: 1.8847... ', '0.1737 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1230... ', 'Training loss: 2.0418... ', '0.1383 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1231... ', 'Training loss: 1.8925... ', '0.1462 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1232... ', 'Training loss: 1.9944... ', '0.1228 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1233

('Epoch: 1/20... ', 'Training Step: 1309... ', 'Training loss: 2.0760... ', '0.1518 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1310... ', 'Training loss: 1.9951... ', '0.1186 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1311... ', 'Training loss: 1.8705... ', '0.1345 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1312... ', 'Training loss: 1.9395... ', '0.0993 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1313... ', 'Training loss: 1.8973... ', '0.1292 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1314... ', 'Training loss: 2.0503... ', '0.1506 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1315... ', 'Training loss: 1.9748... ', '0.1610 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1316... ', 'Training loss: 1.9894... ', '0.1410 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1317... ', 'Training loss: 2.0364... ', '0.1467 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1318... ', 'Training loss: 1.9407... ', '0.1272 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1319

('Epoch: 1/20... ', 'Training Step: 1396... ', 'Training loss: 1.9060... ', '0.1759 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1397... ', 'Training loss: 1.9184... ', '0.1402 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1398... ', 'Training loss: 1.8476... ', '0.1551 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1399... ', 'Training loss: 2.0791... ', '0.1639 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1400... ', 'Training loss: 2.0940... ', '0.1281 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1401... ', 'Training loss: 1.7979... ', '0.1716 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1402... ', 'Training loss: 2.0101... ', '0.1355 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1403... ', 'Training loss: 1.8840... ', '0.1445 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1404... ', 'Training loss: 1.9843... ', '0.1177 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1405... ', 'Training loss: 2.0101... ', '0.1363 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1406

('Epoch: 1/20... ', 'Training Step: 1482... ', 'Training loss: 1.9341... ', '0.1491 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1483... ', 'Training loss: 1.9936... ', '0.1178 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1484... ', 'Training loss: 1.9672... ', '0.1370 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1485... ', 'Training loss: 1.9079... ', '0.1737 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1486... ', 'Training loss: 2.0264... ', '0.1773 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1487... ', 'Training loss: 1.8758... ', '0.1336 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1488... ', 'Training loss: 1.9824... ', '0.1493 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1489... ', 'Training loss: 1.9727... ', '0.1285 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1490... ', 'Training loss: 1.8921... ', '0.1401 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1491... ', 'Training loss: 2.0075... ', '0.1283 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1492

('Epoch: 1/20... ', 'Training Step: 1568... ', 'Training loss: 1.7541... ', '0.1722 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1569... ', 'Training loss: 1.8565... ', '0.1514 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1570... ', 'Training loss: 1.9672... ', '0.1265 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1571... ', 'Training loss: 1.8889... ', '0.1142 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1572... ', 'Training loss: 1.9325... ', '0.1336 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1573... ', 'Training loss: 1.8881... ', '0.1181 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1574... ', 'Training loss: 1.7931... ', '0.1355 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1575... ', 'Training loss: 1.9588... ', '0.1250 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1576... ', 'Training loss: 1.9914... ', '0.1379 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1577... ', 'Training loss: 1.9012... ', '0.1181 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1578

('Epoch: 1/20... ', 'Training Step: 1655... ', 'Training loss: 1.7983... ', '0.1562 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1656... ', 'Training loss: 1.8001... ', '0.1259 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1657... ', 'Training loss: 1.9007... ', '0.1395 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1658... ', 'Training loss: 1.9785... ', '0.1436 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1659... ', 'Training loss: 2.0135... ', '0.1846 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1660... ', 'Training loss: 1.8470... ', '0.1373 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1661... ', 'Training loss: 1.8919... ', '0.1707 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1662... ', 'Training loss: 1.8205... ', '0.1268 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1663... ', 'Training loss: 1.9718... ', '0.1635 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1664... ', 'Training loss: 1.9762... ', '0.1558 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1665

('Epoch: 1/20... ', 'Training Step: 1741... ', 'Training loss: 1.9133... ', '0.1361 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1742... ', 'Training loss: 1.9198... ', '0.1421 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1743... ', 'Training loss: 1.9978... ', '0.1536 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1744... ', 'Training loss: 1.7976... ', '0.1488 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1745... ', 'Training loss: 1.9355... ', '0.1817 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1746... ', 'Training loss: 1.7749... ', '0.1682 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1747... ', 'Training loss: 1.9329... ', '0.1545 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1748... ', 'Training loss: 1.9555... ', '0.1216 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1749... ', 'Training loss: 1.8377... ', '0.1287 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1750... ', 'Training loss: 1.9643... ', '0.1206 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1751

('Epoch: 1/20... ', 'Training Step: 1827... ', 'Training loss: 1.9400... ', '0.1544 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1828... ', 'Training loss: 1.8457... ', '0.1576 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1829... ', 'Training loss: 1.9446... ', '0.1556 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1830... ', 'Training loss: 1.7903... ', '0.1630 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1831... ', 'Training loss: 1.8949... ', '0.1773 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1832... ', 'Training loss: 1.9381... ', '0.1347 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1833... ', 'Training loss: 1.9097... ', '0.1700 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1834... ', 'Training loss: 1.9255... ', '0.1435 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1835... ', 'Training loss: 1.8082... ', '0.1732 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1836... ', 'Training loss: 1.9538... ', '0.1670 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1837

('Epoch: 1/20... ', 'Training Step: 1913... ', 'Training loss: 1.8613... ', '0.1492 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1914... ', 'Training loss: 1.8845... ', '0.1419 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1915... ', 'Training loss: 1.8234... ', '0.1421 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1916... ', 'Training loss: 1.9145... ', '0.1302 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1917... ', 'Training loss: 1.8494... ', '0.1533 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1918... ', 'Training loss: 2.0512... ', '0.1558 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1919... ', 'Training loss: 1.8804... ', '0.1712 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1920... ', 'Training loss: 1.8717... ', '0.1329 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1921... ', 'Training loss: 1.9374... ', '0.1508 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1922... ', 'Training loss: 1.6680... ', '0.1238 sec/batch')
('Epoch: 1/20... ', 'Training Step: 1923

('Epoch: 1/20... ', 'Training Step: 1999... ', 'Training loss: 1.8979... ', '0.1649 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2000... ', 'Training loss: 1.9403... ', '0.1770 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2001... ', 'Training loss: 1.8176... ', '0.1940 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2002... ', 'Training loss: 1.7700... ', '0.1380 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2003... ', 'Training loss: 1.7563... ', '0.1584 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2004... ', 'Training loss: 1.7889... ', '0.1457 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2005... ', 'Training loss: 1.9323... ', '0.1487 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2006... ', 'Training loss: 1.7635... ', '0.1350 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2007... ', 'Training loss: 1.8622... ', '0.1540 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2008... ', 'Training loss: 1.8458... ', '0.1465 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2009

('Epoch: 1/20... ', 'Training Step: 2085... ', 'Training loss: 1.7960... ', '0.1661 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2086... ', 'Training loss: 1.9188... ', '0.1605 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2087... ', 'Training loss: 1.8785... ', '0.1420 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2088... ', 'Training loss: 2.0709... ', '0.1342 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2089... ', 'Training loss: 1.8095... ', '0.1372 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2090... ', 'Training loss: 1.7965... ', '0.1442 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2091... ', 'Training loss: 1.9362... ', '0.1464 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2092... ', 'Training loss: 1.8267... ', '0.1430 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2093... ', 'Training loss: 1.8181... ', '0.1482 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2094... ', 'Training loss: 1.8711... ', '0.1440 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2095

('Epoch: 1/20... ', 'Training Step: 2171... ', 'Training loss: 1.7343... ', '0.1732 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2172... ', 'Training loss: 1.8715... ', '0.1722 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2173... ', 'Training loss: 1.9749... ', '0.1809 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2174... ', 'Training loss: 1.7670... ', '0.1410 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2175... ', 'Training loss: 1.9718... ', '0.1594 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2176... ', 'Training loss: 1.9115... ', '0.1359 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2177... ', 'Training loss: 1.9027... ', '0.1368 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2178... ', 'Training loss: 1.9446... ', '0.1253 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2179... ', 'Training loss: 1.9000... ', '0.1375 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2180... ', 'Training loss: 1.9583... ', '0.1365 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2181

('Epoch: 1/20... ', 'Training Step: 2257... ', 'Training loss: 1.8876... ', '0.1537 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2258... ', 'Training loss: 1.8117... ', '0.1203 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2259... ', 'Training loss: 1.7132... ', '0.1565 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2260... ', 'Training loss: 2.0203... ', '0.1396 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2261... ', 'Training loss: 2.0105... ', '0.1461 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2262... ', 'Training loss: 1.7198... ', '0.1528 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2263... ', 'Training loss: 1.7395... ', '0.1705 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2264... ', 'Training loss: 1.9026... ', '0.1713 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2265... ', 'Training loss: 1.7672... ', '0.2014 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2266... ', 'Training loss: 1.8687... ', '0.1590 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2267

('Epoch: 1/20... ', 'Training Step: 2343... ', 'Training loss: 1.8569... ', '0.1733 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2344... ', 'Training loss: 1.8423... ', '0.1432 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2345... ', 'Training loss: 1.8212... ', '0.1470 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2346... ', 'Training loss: 1.6919... ', '0.1318 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2347... ', 'Training loss: 1.9268... ', '0.1515 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2348... ', 'Training loss: 1.7926... ', '0.1202 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2349... ', 'Training loss: 1.9209... ', '0.1365 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2350... ', 'Training loss: 1.9740... ', '0.1494 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2351... ', 'Training loss: 1.9971... ', '0.1504 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2352... ', 'Training loss: 1.9993... ', '0.1117 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2353

('Epoch: 1/20... ', 'Training Step: 2429... ', 'Training loss: 1.9463... ', '0.1535 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2430... ', 'Training loss: 1.8477... ', '0.1268 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2431... ', 'Training loss: 1.9208... ', '0.1524 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2432... ', 'Training loss: 1.9829... ', '0.1383 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2433... ', 'Training loss: 1.9640... ', '0.1685 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2434... ', 'Training loss: 1.8411... ', '0.1414 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2435... ', 'Training loss: 1.7374... ', '0.1475 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2436... ', 'Training loss: 1.8448... ', '0.1338 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2437... ', 'Training loss: 1.7988... ', '0.1508 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2438... ', 'Training loss: 1.8971... ', '0.1364 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2439

('Epoch: 1/20... ', 'Training Step: 2515... ', 'Training loss: 1.7962... ', '0.2087 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2516... ', 'Training loss: 1.9038... ', '0.1393 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2517... ', 'Training loss: 1.7878... ', '0.1343 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2518... ', 'Training loss: 1.8900... ', '0.1169 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2519... ', 'Training loss: 1.9059... ', '0.1460 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2520... ', 'Training loss: 1.9266... ', '0.1146 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2521... ', 'Training loss: 1.8366... ', '0.1380 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2522... ', 'Training loss: 1.8204... ', '0.1228 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2523... ', 'Training loss: 1.7877... ', '0.1562 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2524... ', 'Training loss: 1.9544... ', '0.1341 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2525

('Epoch: 1/20... ', 'Training Step: 2601... ', 'Training loss: 1.7918... ', '0.1493 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2602... ', 'Training loss: 1.8350... ', '0.1254 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2603... ', 'Training loss: 1.8762... ', '0.1527 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2604... ', 'Training loss: 1.8729... ', '0.1254 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2605... ', 'Training loss: 1.7967... ', '0.1560 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2606... ', 'Training loss: 1.7485... ', '0.1327 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2607... ', 'Training loss: 1.8154... ', '0.1433 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2608... ', 'Training loss: 1.9278... ', '0.1283 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2609... ', 'Training loss: 1.7191... ', '0.1372 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2610... ', 'Training loss: 1.8759... ', '0.1390 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2611

('Epoch: 1/20... ', 'Training Step: 2687... ', 'Training loss: 1.8162... ', '0.1832 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2688... ', 'Training loss: 1.7818... ', '0.1818 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2689... ', 'Training loss: 1.7609... ', '0.1674 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2690... ', 'Training loss: 1.9372... ', '0.1481 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2691... ', 'Training loss: 1.9344... ', '0.1424 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2692... ', 'Training loss: 1.8630... ', '0.1180 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2693... ', 'Training loss: 1.7703... ', '0.1356 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2694... ', 'Training loss: 1.9577... ', '0.1272 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2695... ', 'Training loss: 2.0171... ', '0.1483 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2696... ', 'Training loss: 1.8327... ', '0.1283 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2697

('Epoch: 1/20... ', 'Training Step: 2773... ', 'Training loss: 1.7468... ', '0.1661 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2774... ', 'Training loss: 1.8714... ', '0.1300 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2775... ', 'Training loss: 1.8690... ', '0.1282 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2776... ', 'Training loss: 1.8352... ', '0.1440 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2777... ', 'Training loss: 1.8876... ', '0.1327 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2778... ', 'Training loss: 1.7385... ', '0.1335 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2779... ', 'Training loss: 1.7454... ', '0.1502 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2780... ', 'Training loss: 1.7629... ', '0.1213 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2781... ', 'Training loss: 1.7257... ', '0.1524 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2782... ', 'Training loss: 1.9132... ', '0.1255 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2783

('Epoch: 1/20... ', 'Training Step: 2860... ', 'Training loss: 1.7941... ', '0.1376 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2861... ', 'Training loss: 1.8947... ', '0.1463 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2862... ', 'Training loss: 1.7047... ', '0.1635 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2863... ', 'Training loss: 1.8318... ', '0.1347 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2864... ', 'Training loss: 1.8749... ', '0.1467 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2865... ', 'Training loss: 1.7267... ', '0.1219 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2866... ', 'Training loss: 1.7937... ', '0.1554 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2867... ', 'Training loss: 1.7339... ', '0.1449 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2868... ', 'Training loss: 1.7892... ', '0.1583 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2869... ', 'Training loss: 1.9189... ', '0.1539 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2870

('Epoch: 1/20... ', 'Training Step: 2946... ', 'Training loss: 1.8696... ', '0.1193 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2947... ', 'Training loss: 1.8292... ', '0.1704 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2948... ', 'Training loss: 1.7842... ', '0.1450 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2949... ', 'Training loss: 1.6608... ', '0.1435 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2950... ', 'Training loss: 1.6065... ', '0.1433 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2951... ', 'Training loss: 1.7949... ', '0.1328 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2952... ', 'Training loss: 1.7762... ', '0.1272 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2953... ', 'Training loss: 1.7759... ', '0.1536 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2954... ', 'Training loss: 1.7464... ', '0.1599 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2955... ', 'Training loss: 1.6943... ', '0.1550 sec/batch')
('Epoch: 1/20... ', 'Training Step: 2956

('Epoch: 1/20... ', 'Training Step: 3033... ', 'Training loss: 1.8428... ', '0.1955 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3034... ', 'Training loss: 1.8523... ', '0.1389 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3035... ', 'Training loss: 1.6355... ', '0.1377 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3036... ', 'Training loss: 1.9743... ', '0.1315 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3037... ', 'Training loss: 1.8203... ', '0.1688 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3038... ', 'Training loss: 1.9705... ', '0.1343 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3039... ', 'Training loss: 1.7664... ', '0.1699 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3040... ', 'Training loss: 1.9288... ', '0.1665 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3041... ', 'Training loss: 1.8046... ', '0.1544 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3042... ', 'Training loss: 1.8630... ', '0.1642 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3043

('Epoch: 1/20... ', 'Training Step: 3119... ', 'Training loss: 1.7825... ', '0.1710 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3120... ', 'Training loss: 1.7542... ', '0.1453 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3121... ', 'Training loss: 1.7905... ', '0.1390 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3122... ', 'Training loss: 1.7929... ', '0.1388 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3123... ', 'Training loss: 1.9260... ', '0.1422 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3124... ', 'Training loss: 1.7904... ', '0.1383 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3125... ', 'Training loss: 1.8251... ', '0.1687 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3126... ', 'Training loss: 1.8337... ', '0.1575 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3127... ', 'Training loss: 1.8998... ', '0.1695 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3128... ', 'Training loss: 1.7878... ', '0.1445 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3129

('Epoch: 1/20... ', 'Training Step: 3206... ', 'Training loss: 1.8442... ', '0.1415 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3207... ', 'Training loss: 1.8281... ', '0.1490 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3208... ', 'Training loss: 1.9146... ', '0.2671 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3209... ', 'Training loss: 1.7409... ', '0.3468 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3210... ', 'Training loss: 1.7392... ', '0.2285 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3211... ', 'Training loss: 1.9292... ', '0.1398 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3212... ', 'Training loss: 1.9444... ', '0.1431 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3213... ', 'Training loss: 1.8920... ', '0.1801 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3214... ', 'Training loss: 1.8778... ', '0.1686 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3215... ', 'Training loss: 1.8324... ', '0.1429 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3216

('Epoch: 1/20... ', 'Training Step: 3293... ', 'Training loss: 1.7957... ', '0.1314 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3294... ', 'Training loss: 1.8346... ', '0.1479 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3295... ', 'Training loss: 1.8982... ', '0.1492 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3296... ', 'Training loss: 1.9572... ', '0.1488 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3297... ', 'Training loss: 1.9107... ', '0.1912 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3298... ', 'Training loss: 1.8427... ', '0.1647 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3299... ', 'Training loss: 1.8345... ', '0.1385 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3300... ', 'Training loss: 1.9188... ', '0.1636 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3301... ', 'Training loss: 1.8918... ', '0.1587 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3302... ', 'Training loss: 1.9220... ', '0.1622 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3303

('Epoch: 1/20... ', 'Training Step: 3379... ', 'Training loss: 1.6014... ', '0.2044 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3380... ', 'Training loss: 1.6884... ', '0.1552 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3381... ', 'Training loss: 1.7394... ', '0.1665 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3382... ', 'Training loss: 1.7453... ', '0.1584 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3383... ', 'Training loss: 1.7441... ', '0.1655 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3384... ', 'Training loss: 1.7837... ', '0.1691 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3385... ', 'Training loss: 1.7801... ', '0.1910 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3386... ', 'Training loss: 1.7269... ', '0.2134 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3387... ', 'Training loss: 1.8697... ', '0.2353 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3388... ', 'Training loss: 1.8980... ', '0.1874 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3389

('Epoch: 1/20... ', 'Training Step: 3465... ', 'Training loss: 1.7233... ', '0.1435 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3466... ', 'Training loss: 1.6300... ', '0.1444 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3467... ', 'Training loss: 1.6133... ', '0.1361 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3468... ', 'Training loss: 1.7634... ', '0.1250 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3469... ', 'Training loss: 1.8943... ', '0.1409 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3470... ', 'Training loss: 1.7743... ', '0.1339 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3471... ', 'Training loss: 1.8090... ', '0.1621 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3472... ', 'Training loss: 1.7340... ', '0.1338 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3473... ', 'Training loss: 1.9055... ', '0.1319 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3474... ', 'Training loss: 1.7892... ', '0.1198 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3475

('Epoch: 1/20... ', 'Training Step: 3551... ', 'Training loss: 1.8425... ', '0.2522 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3552... ', 'Training loss: 1.8287... ', '0.2757 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3553... ', 'Training loss: 1.9305... ', '0.1603 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3554... ', 'Training loss: 1.8887... ', '0.1545 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3555... ', 'Training loss: 1.6614... ', '0.1913 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3556... ', 'Training loss: 1.9422... ', '0.1464 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3557... ', 'Training loss: 1.6767... ', '0.1458 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3558... ', 'Training loss: 1.5943... ', '0.1595 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3559... ', 'Training loss: 1.9401... ', '0.1711 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3560... ', 'Training loss: 1.7898... ', '0.1832 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3561

('Epoch: 1/20... ', 'Training Step: 3637... ', 'Training loss: 1.8178... ', '0.2946 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3638... ', 'Training loss: 1.8497... ', '0.2762 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3639... ', 'Training loss: 1.9275... ', '0.2668 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3640... ', 'Training loss: 1.7641... ', '0.2899 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3641... ', 'Training loss: 1.9195... ', '0.2438 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3642... ', 'Training loss: 1.8906... ', '0.3853 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3643... ', 'Training loss: 2.0272... ', '0.1968 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3644... ', 'Training loss: 1.9495... ', '0.2810 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3645... ', 'Training loss: 1.8383... ', '0.2372 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3646... ', 'Training loss: 1.6529... ', '0.3433 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3647

('Epoch: 1/20... ', 'Training Step: 3724... ', 'Training loss: 1.9086... ', '0.2073 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3725... ', 'Training loss: 1.9302... ', '0.1272 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3726... ', 'Training loss: 1.8993... ', '0.1656 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3727... ', 'Training loss: 2.0158... ', '0.1700 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3728... ', 'Training loss: 1.9840... ', '0.1753 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3729... ', 'Training loss: 1.9662... ', '0.1932 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3730... ', 'Training loss: 2.0204... ', '0.2340 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3731... ', 'Training loss: 1.8673... ', '0.1678 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3732... ', 'Training loss: 1.9395... ', '0.1749 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3733... ', 'Training loss: 1.8128... ', '0.1567 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3734

('Epoch: 1/20... ', 'Training Step: 3811... ', 'Training loss: 1.7708... ', '0.1712 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3812... ', 'Training loss: 1.8911... ', '0.1328 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3813... ', 'Training loss: 1.6870... ', '0.1461 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3814... ', 'Training loss: 1.7191... ', '0.1655 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3815... ', 'Training loss: 2.0074... ', '0.1576 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3816... ', 'Training loss: 2.4602... ', '0.1739 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3817... ', 'Training loss: 2.4573... ', '0.1618 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3818... ', 'Training loss: 2.4160... ', '0.1318 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3819... ', 'Training loss: 2.4242... ', '0.1543 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3820... ', 'Training loss: 2.3716... ', '0.1388 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3821

('Epoch: 1/20... ', 'Training Step: 3897... ', 'Training loss: 2.0184... ', '0.1614 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3898... ', 'Training loss: 1.8491... ', '0.1234 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3899... ', 'Training loss: 1.9223... ', '0.1251 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3900... ', 'Training loss: 1.9443... ', '0.1158 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3901... ', 'Training loss: 1.8748... ', '0.1489 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3902... ', 'Training loss: 2.1627... ', '0.1366 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3903... ', 'Training loss: 1.9833... ', '0.1615 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3904... ', 'Training loss: 1.9557... ', '0.1409 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3905... ', 'Training loss: 2.1388... ', '0.1635 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3906... ', 'Training loss: 2.1070... ', '0.1336 sec/batch')
('Epoch: 1/20... ', 'Training Step: 3907

('Epoch: 2/20... ', 'Training Step: 3983... ', 'Training loss: 1.7498... ', '0.2067 sec/batch')
('Epoch: 2/20... ', 'Training Step: 3984... ', 'Training loss: 1.8406... ', '0.1549 sec/batch')
('Epoch: 2/20... ', 'Training Step: 3985... ', 'Training loss: 1.6319... ', '0.1427 sec/batch')
('Epoch: 2/20... ', 'Training Step: 3986... ', 'Training loss: 1.7723... ', '0.1378 sec/batch')
('Epoch: 2/20... ', 'Training Step: 3987... ', 'Training loss: 1.7501... ', '0.1559 sec/batch')
('Epoch: 2/20... ', 'Training Step: 3988... ', 'Training loss: 1.7486... ', '0.1368 sec/batch')
('Epoch: 2/20... ', 'Training Step: 3989... ', 'Training loss: 1.8305... ', '0.1570 sec/batch')
('Epoch: 2/20... ', 'Training Step: 3990... ', 'Training loss: 1.9373... ', '0.1333 sec/batch')
('Epoch: 2/20... ', 'Training Step: 3991... ', 'Training loss: 1.8302... ', '0.1925 sec/batch')
('Epoch: 2/20... ', 'Training Step: 3992... ', 'Training loss: 1.7581... ', '0.1324 sec/batch')
('Epoch: 2/20... ', 'Training Step: 3993

('Epoch: 2/20... ', 'Training Step: 4069... ', 'Training loss: 1.8012... ', '0.1792 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4070... ', 'Training loss: 1.7288... ', '0.1402 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4071... ', 'Training loss: 1.9077... ', '0.1471 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4072... ', 'Training loss: 1.7517... ', '0.1289 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4073... ', 'Training loss: 1.8698... ', '0.1526 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4074... ', 'Training loss: 1.7089... ', '0.1443 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4075... ', 'Training loss: 1.7796... ', '0.1775 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4076... ', 'Training loss: 1.7711... ', '0.1248 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4077... ', 'Training loss: 1.6893... ', '0.1596 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4078... ', 'Training loss: 1.7803... ', '0.1079 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4079

('Epoch: 2/20... ', 'Training Step: 4155... ', 'Training loss: 1.7328... ', '0.1752 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4156... ', 'Training loss: 1.8055... ', '0.1608 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4157... ', 'Training loss: 1.6340... ', '0.2056 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4158... ', 'Training loss: 1.7919... ', '0.1860 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4159... ', 'Training loss: 1.7815... ', '0.2103 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4160... ', 'Training loss: 1.8402... ', '0.1631 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4161... ', 'Training loss: 1.7921... ', '0.2457 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4162... ', 'Training loss: 1.6890... ', '0.1741 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4163... ', 'Training loss: 1.7544... ', '0.1873 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4164... ', 'Training loss: 1.8954... ', '0.1601 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4165

('Epoch: 2/20... ', 'Training Step: 4241... ', 'Training loss: 1.8250... ', '0.1983 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4242... ', 'Training loss: 1.7963... ', '0.1482 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4243... ', 'Training loss: 1.9318... ', '0.1697 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4244... ', 'Training loss: 1.8382... ', '0.1463 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4245... ', 'Training loss: 1.9323... ', '0.1491 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4246... ', 'Training loss: 1.8204... ', '0.1146 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4247... ', 'Training loss: 1.7916... ', '0.1429 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4248... ', 'Training loss: 1.9312... ', '0.1230 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4249... ', 'Training loss: 1.8053... ', '0.1442 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4250... ', 'Training loss: 1.7721... ', '0.1217 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4251

('Epoch: 2/20... ', 'Training Step: 4327... ', 'Training loss: 1.9041... ', '0.1371 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4328... ', 'Training loss: 1.9084... ', '0.1687 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4329... ', 'Training loss: 1.7730... ', '0.1390 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4330... ', 'Training loss: 1.8924... ', '0.1212 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4331... ', 'Training loss: 1.8428... ', '0.1601 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4332... ', 'Training loss: 1.8039... ', '0.1777 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4333... ', 'Training loss: 1.8506... ', '0.1690 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4334... ', 'Training loss: 1.6764... ', '0.1702 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4335... ', 'Training loss: 1.9069... ', '0.1635 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4336... ', 'Training loss: 1.7605... ', '0.1513 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4337

('Epoch: 2/20... ', 'Training Step: 4413... ', 'Training loss: 1.8332... ', '0.1968 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4414... ', 'Training loss: 1.7117... ', '0.1843 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4415... ', 'Training loss: 1.8263... ', '0.1597 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4416... ', 'Training loss: 1.8625... ', '0.2823 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4417... ', 'Training loss: 1.9418... ', '0.1540 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4418... ', 'Training loss: 1.7154... ', '0.1532 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4419... ', 'Training loss: 1.7075... ', '0.1517 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4420... ', 'Training loss: 1.8574... ', '0.1788 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4421... ', 'Training loss: 1.7674... ', '0.1487 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4422... ', 'Training loss: 1.7573... ', '0.1787 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4423

('Epoch: 2/20... ', 'Training Step: 4500... ', 'Training loss: 1.8146... ', '0.1545 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4501... ', 'Training loss: 1.9543... ', '0.1386 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4502... ', 'Training loss: 1.7848... ', '0.2085 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4503... ', 'Training loss: 1.6980... ', '0.1603 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4504... ', 'Training loss: 1.7774... ', '0.1869 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4505... ', 'Training loss: 1.8365... ', '0.1804 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4506... ', 'Training loss: 1.8296... ', '0.1862 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4507... ', 'Training loss: 1.5835... ', '0.1675 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4508... ', 'Training loss: 1.6968... ', '0.1849 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4509... ', 'Training loss: 1.6715... ', '0.1449 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4510

('Epoch: 2/20... ', 'Training Step: 4587... ', 'Training loss: 1.7441... ', '0.1847 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4588... ', 'Training loss: 1.7011... ', '0.2537 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4589... ', 'Training loss: 1.7156... ', '0.1710 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4590... ', 'Training loss: 1.6239... ', '0.1764 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4591... ', 'Training loss: 1.6581... ', '0.1761 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4592... ', 'Training loss: 1.7684... ', '0.1381 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4593... ', 'Training loss: 1.8466... ', '0.1727 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4594... ', 'Training loss: 1.8008... ', '0.1445 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4595... ', 'Training loss: 1.6593... ', '0.1387 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4596... ', 'Training loss: 1.8169... ', '0.1206 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4597

('Epoch: 2/20... ', 'Training Step: 4673... ', 'Training loss: 1.7882... ', '0.1716 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4674... ', 'Training loss: 1.8361... ', '0.2106 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4675... ', 'Training loss: 1.8029... ', '0.2600 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4676... ', 'Training loss: 1.7991... ', '0.1877 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4677... ', 'Training loss: 1.8151... ', '0.1770 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4678... ', 'Training loss: 1.7632... ', '0.1542 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4679... ', 'Training loss: 1.7777... ', '0.1762 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4680... ', 'Training loss: 1.7947... ', '0.1606 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4681... ', 'Training loss: 1.7944... ', '0.1404 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4682... ', 'Training loss: 1.8528... ', '0.1382 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4683

('Epoch: 2/20... ', 'Training Step: 4759... ', 'Training loss: 1.8526... ', '0.1867 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4760... ', 'Training loss: 1.7417... ', '0.1450 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4761... ', 'Training loss: 1.8119... ', '0.1483 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4762... ', 'Training loss: 1.6518... ', '0.1503 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4763... ', 'Training loss: 1.7597... ', '0.1400 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4764... ', 'Training loss: 1.7987... ', '0.1520 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4765... ', 'Training loss: 1.6918... ', '0.1535 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4766... ', 'Training loss: 1.6483... ', '0.1337 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4767... ', 'Training loss: 1.8243... ', '0.1455 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4768... ', 'Training loss: 1.6427... ', '0.1357 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4769

('Epoch: 2/20... ', 'Training Step: 4845... ', 'Training loss: 1.9016... ', '0.1473 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4846... ', 'Training loss: 1.7804... ', '0.1536 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4847... ', 'Training loss: 1.7730... ', '0.1522 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4848... ', 'Training loss: 1.9903... ', '0.1525 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4849... ', 'Training loss: 1.7317... ', '0.1465 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4850... ', 'Training loss: 1.6872... ', '0.1475 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4851... ', 'Training loss: 1.9885... ', '0.1341 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4852... ', 'Training loss: 1.9926... ', '0.1318 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4853... ', 'Training loss: 1.8803... ', '0.1418 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4854... ', 'Training loss: 1.8265... ', '0.1394 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4855

('Epoch: 2/20... ', 'Training Step: 4931... ', 'Training loss: 1.6719... ', '0.1457 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4932... ', 'Training loss: 1.7579... ', '0.1424 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4933... ', 'Training loss: 1.6904... ', '0.1330 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4934... ', 'Training loss: 1.7475... ', '0.1563 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4935... ', 'Training loss: 1.8186... ', '0.1424 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4936... ', 'Training loss: 1.8105... ', '0.1480 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4937... ', 'Training loss: 1.6994... ', '0.1537 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4938... ', 'Training loss: 1.7142... ', '0.1429 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4939... ', 'Training loss: 1.7352... ', '0.1396 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4940... ', 'Training loss: 1.6702... ', '0.2960 sec/batch')
('Epoch: 2/20... ', 'Training Step: 4941

('Epoch: 2/20... ', 'Training Step: 5017... ', 'Training loss: 1.6792... ', '0.1300 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5018... ', 'Training loss: 1.7286... ', '0.1346 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5019... ', 'Training loss: 1.6199... ', '0.1326 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5020... ', 'Training loss: 1.7843... ', '0.1193 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5021... ', 'Training loss: 1.8158... ', '0.1349 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5022... ', 'Training loss: 1.7685... ', '0.1262 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5023... ', 'Training loss: 1.6537... ', '0.1294 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5024... ', 'Training loss: 1.7102... ', '0.1279 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5025... ', 'Training loss: 1.7638... ', '0.1247 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5026... ', 'Training loss: 1.6830... ', '0.1525 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5027

('Epoch: 2/20... ', 'Training Step: 5103... ', 'Training loss: 1.6585... ', '0.1598 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5104... ', 'Training loss: 1.8533... ', '0.1473 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5105... ', 'Training loss: 1.6774... ', '0.1388 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5106... ', 'Training loss: 1.8555... ', '0.1337 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5107... ', 'Training loss: 1.8400... ', '0.1627 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5108... ', 'Training loss: 1.8361... ', '0.1705 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5109... ', 'Training loss: 1.7713... ', '0.1441 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5110... ', 'Training loss: 1.8816... ', '0.1327 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5111... ', 'Training loss: 1.6956... ', '0.1695 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5112... ', 'Training loss: 1.7734... ', '0.1517 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5113

('Epoch: 2/20... ', 'Training Step: 5189... ', 'Training loss: 1.7107... ', '0.1271 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5190... ', 'Training loss: 1.7641... ', '0.1223 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5191... ', 'Training loss: 1.7817... ', '0.1209 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5192... ', 'Training loss: 1.8309... ', '0.1303 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5193... ', 'Training loss: 1.6439... ', '0.1874 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5194... ', 'Training loss: 1.7089... ', '0.1514 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5195... ', 'Training loss: 1.8660... ', '0.1831 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5196... ', 'Training loss: 1.7402... ', '0.1413 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5197... ', 'Training loss: 1.8921... ', '0.1625 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5198... ', 'Training loss: 1.8085... ', '0.1963 sec/batch')
('Epoch: 2/20... ', 'Training Step: 5199

#### Saved checkpoints

Read up on saving and loading checkpoints here: https://www.tensorflow.org/programmers_guide/variables

In [40]:
tf.train.get_checkpoint_state('checkpoints')

model_checkpoint_path: "checkpoints/i5200_l128.ckpt"
all_model_checkpoint_paths: "checkpoints/i200_l128.ckpt"
all_model_checkpoint_paths: "checkpoints/i400_l128.ckpt"
all_model_checkpoint_paths: "checkpoints/i600_l128.ckpt"
all_model_checkpoint_paths: "checkpoints/i800_l128.ckpt"
all_model_checkpoint_paths: "checkpoints/i1000_l128.ckpt"
all_model_checkpoint_paths: "checkpoints/i1200_l128.ckpt"
all_model_checkpoint_paths: "checkpoints/i1400_l128.ckpt"
all_model_checkpoint_paths: "checkpoints/i1600_l128.ckpt"
all_model_checkpoint_paths: "checkpoints/i1800_l128.ckpt"
all_model_checkpoint_paths: "checkpoints/i2000_l128.ckpt"
all_model_checkpoint_paths: "checkpoints/i2200_l128.ckpt"
all_model_checkpoint_paths: "checkpoints/i2400_l128.ckpt"
all_model_checkpoint_paths: "checkpoints/i2600_l128.ckpt"
all_model_checkpoint_paths: "checkpoints/i2800_l128.ckpt"
all_model_checkpoint_paths: "checkpoints/i3000_l128.ckpt"
all_model_checkpoint_paths: "checkpoints/i3200_l128.ckpt"
all_model_checkpoint_pa

## Sampling

Now that the network is trained, we'll can use it to generate new text. The idea is that we pass in a character, then the network will predict the next character. We can use the new one, to predict the next one. And we keep doing this to generate all new text. I also included some functionality to prime the network with some text by passing in a string and building up a state from that.

The network gives us predictions for each character. To reduce noise and make things a little less random, I'm going to only choose a new character from the top N most likely characters.



In [17]:
def pick_top_n(preds, vocab_size, top_n=5):
    p = np.squeeze(preds)
    p[np.argsort(p)[:-top_n]] = 0
    p = p / np.sum(p)
    c = np.random.choice(vocab_size, 1, p=p)[0]
    return c

In [43]:
def sample(checkpoint, n_samples, lstm_size, vocab_size, prime="The "):
    samples = [c for c in prime]
    model = CharRNN(len(vocab), lstm_size=lstm_size, sampling=True)
    saver = tf.train.Saver()
    with tf.Session() as sess:
        saver.restore(sess, checkpoint)
        new_state = sess.run(model.initial_state)
        for c in prime:
            x = np.zeros((1, 1))
            x[0,0] = vocab_to_int[c]
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

        c = pick_top_n(preds, len(vocab))
        samples.append(int_to_vocab[c])

        for i in range(n_samples):
            x[0,0] = c
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

            c = pick_top_n(preds, len(vocab))
            samples.append(int_to_vocab[c])
        
    return ''.join(samples)

Here, pass in the path to a checkpoint and sample from the network.

In [44]:
tf.train.latest_checkpoint('checkpoints')

u'checkpoints/i5200_l128.ckpt'

In [45]:
checkpoint = tf.train.latest_checkpoint('checkpoints')
samp = sample(checkpoint, 2000, lstm_size, len(vocab), prime="Far")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints/i5200_l128.ckpt
Farange to the herited of the stome,
though
at her horses to them to the to she would so she with it what she was to be was is. Anna sat that all to be hen that had the persing of the children while, her were."

"Well as the horm to be how some will
the strothing to him to take, he with
so hand of how to be than at the prostarences them over of them his
sange of is as
the somesher that had till there were his harss and the trackent of the shors to be hoos had
take and horried
the parilated to be the thought with she said hand, and was sent his wonder, went his his to take to him," said Levin to
beliaged
her has had her, all all he shuses a corsition and their prepend of her hand her, and a thing who to her was he saw to her thought.

"I shate his tome had his come in it of her. "I door as sants and where," he
that he cheak his
head,
and he was too her so this,
better there," she said all it sease to be he chat her wo

In [ ]:
checkpoint = 'checkpoints/i200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

In [ ]:
checkpoint = 'checkpoints/i600_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

In [ ]:
checkpoint = 'checkpoints/i1200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)